import { useEffect, useRef, useState } from 'react';
import type { WorkflowId } from './types';
import { Badge, Icon, workflowIcons, workflowLabels } from './ui';

export default function NewCase({initialWorkflow,busy,error,onClose,onCreate}:{initialWorkflow:WorkflowId;busy:boolean;error?:string;onClose:()=>void;onCreate:(body:unknown)=>void}) {
  const [workflow,setWorkflow]=useState(initialWorkflow);
  const [title,setTitle]=useState('');
  const [protocol,setProtocol]=useState('nfs');
  const [description,setDescription]=useState('');
  const [rw,setRw]=useState('randwrite');
  const [bs,setBs]=useState('4k');
  const [iodepth,setIodepth]=useState(64);
  const [numjobs,setNumjobs]=useState(8);
  const [vmCount,setVmCount]=useState(1);
  const [baseline,setBaseline]=useState('');
  const [target,setTarget]=useState('');
  const dialog=useRef<HTMLDivElement>(null);
  const latest=useRef({busy,onClose});latest.current={busy,onClose};
  useEffect(()=>{const previous=document.body.style.overflow;const previousFocus=document.activeElement as HTMLElement|null;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLInputElement>('input')?.focus();const handle=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!latest.current.busy)latest.current.onClose();if(event.key==='Tab'&&dialog.current){const elements=Array.from(dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]), input, select, textarea'));const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',handle);previousFocus?.focus();};},[]);
  function submit(event:React.FormEvent) {event.preventDefault();onCreate({title:title.trim(),workflow_id:workflow,protocol,description:description.trim(),owner:'性能专家团队',fio:{rw,bs,iodepth,numjobs,vm_count:vmCount},baseline_version:baseline.trim()||undefined,target_version:target.trim()||undefined});}
  return <div className="modal-backdrop" onClick={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><div ref={dialog} className="modal" role="dialog" aria-modal="true" aria-labelledby="new-case-title"><div className="modal-header"><div><h2 id="new-case-title">新建案例</h2></div><button className="icon-button" onClick={onClose} disabled={busy} aria-label="关闭新建案例窗口"><Icon name="close"/></button></div><form onSubmit={submit}><div className="modal-body">
    {error&&<div className="alert alert-error" role="alert"><Icon name="info" size={17}/>{error}</div>}
    <label className="field-label">业务场景</label><div className="workflow-selector">{(['version','poc','research'] as const).map(id=><button className={`workflow-choice ${workflow===id?'active':''}`} type="button" key={id} onClick={()=>setWorkflow(id)}><Icon name={workflowIcons[id]} size={22}/><span>{workflowLabels[id]}</span>{workflow===id&&<Icon name="check" size={15}/>}</button>)}</div>
    <div className="field"><label htmlFor="case-title">案例名称 <span>*</span></label><input id="case-title" value={title} onChange={event=>setTitle(event.target.value)} placeholder={workflow==='version'?'例如：新版本 NFS 随机写性能下降':workflow==='poc'?'例如：客户 POC 单虚拟机性能调优':'例如：IO 线程模型预研实验'} required minLength={2} maxLength={120}/></div>
    <div className="field"><label htmlFor="case-context">问题背景与目标 <span>*</span></label><textarea id="case-context" value={description} onChange={event=>setDescription(event.target.value)} rows={3} placeholder="描述当前现象、期望指标、已知环境和已经做过的尝试…" required minLength={2} maxLength={4000}/></div>
    <div className="form-section-label"><Icon name="activity" size={16}/><span>fio 测试场景</span><Badge>虚拟机内部执行</Badge></div>
    <div className="form-grid three-col"><div className="field"><label htmlFor="case-protocol">存储协议</label><select id="case-protocol" value={protocol} onChange={event=>setProtocol(event.target.value)}><option value="nfs">NFS</option><option value="vhost">vhost</option><option value="iscsi">iSCSI</option></select></div><div className="field"><label htmlFor="case-rw">读写模型</label><select id="case-rw" value={rw} onChange={event=>setRw(event.target.value)}><option value="randwrite">随机写 / randwrite</option><option value="randread">随机读 / randread</option><option value="randrw">混合随机 / randrw</option><option value="read">顺序读 / read</option><option value="write">顺序写 / write</option></select></div><div className="field"><label htmlFor="case-bs">块大小</label><select id="case-bs" value={bs} onChange={event=>setBs(event.target.value)}><option>4k</option><option>8k</option><option>16k</option><option>64k</option><option>128k</option><option>1m</option></select></div><div className="field"><label htmlFor="case-depth">iodepth</label><input id="case-depth" type="number" value={iodepth} min={1} max={1024} onChange={event=>setIodepth(Number(event.target.value))} required/></div><div className="field"><label htmlFor="case-jobs">numjobs</label><input id="case-jobs" type="number" value={numjobs} min={1} max={128} onChange={event=>setNumjobs(Number(event.target.value))} required/></div><div className="field"><label htmlFor="case-vm">虚拟机数量</label><input id="case-vm" type="number" value={vmCount} min={1} max={128} onChange={event=>setVmCount(Number(event.target.value))} required/></div></div>
    <div className="form-grid"><div className="field"><label htmlFor="case-baseline">基线版本 <small>可选</small></label><input id="case-baseline" value={baseline} onChange={event=>setBaseline(event.target.value)} placeholder="例如：release-baseline" maxLength={80}/></div><div className="field"><label htmlFor="case-target">目标版本 <small>可选</small></label><input id="case-target" value={target} onChange={event=>setTarget(event.target.value)} placeholder="例如：build-candidate" maxLength={80}/></div></div>
    <div className="scope-note"><Icon name="info" size={16}/><span>三节点 POC 聚合副本：数据存到本地和一个远端；当前执行模拟流程。</span></div>
    </div><div className="modal-footer"><div><button className="button button-secondary" type="button" onClick={onClose} disabled={busy}>取消</button><button className="button button-primary" type="submit" disabled={busy}><Icon name="plus" size={16}/>{busy?'创建中…':'创建案例'}</button></div></div></form></div></div>;
}
