import { useState } from 'react';
import type { Knowledge, Tool, Workflow, WorkflowId } from './types';
import { Badge, Empty, Icon, formatContent, workflowIcons, workflowLabels } from './ui';

export function KnowledgePage({items}:{items:Knowledge[]}) {
  const [query,setQuery]=useState('');
  const [category,setCategory]=useState('all');
  const [expanded,setExpanded]=useState<string|null>(null);
  const categories=Array.from(new Set(items.map(item=>item.category||'专家知识')));
  const filtered=items.filter(item=>(category==='all'||item.category===category)&&`${item.title} ${item.summary||''} ${(item.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="page-heading"><h1>专家知识库</h1></div><div className="knowledge-banner"><span className="knowledge-banner-icon"><Icon name="book" size={30}/></span><div><h2>资料来源</h2><p>架构资料来自产品 IO 文档；演示案例与专家反馈单独标记。</p></div><div className="knowledge-count"><strong>{items.length}</strong><span>知识条目</span></div></div><section className="panel"><div className="case-filters"><div className="segmented">{['all',...categories].map(value=><button className={category===value?'active':''} key={value} onClick={()=>setCategory(value)}>{value==='all'?'全部知识':value}</button>)}</div><label className="search-field"><Icon name="search" size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索架构、方法或经验" aria-label="搜索知识库"/></label></div><div className="knowledge-list">{filtered.map(item=><article className={`knowledge-item ${expanded===item.id?'expanded':''}`} key={item.id}><button className="knowledge-item-heading" onClick={()=>setExpanded(expanded===item.id?null:item.id)}><span className="document-icon"><Icon name={item.source==='user'?'server':item.source==='mock'?'flask':'book'}/></span><div><div className="knowledge-item-title"><h3>{item.title}</h3><Badge tone={item.source==='user'?'teal':item.source==='mock'?'amber':'blue'}>{item.source==='user'?'产品事实':item.source==='mock'?'模拟案例':'定位方法'}</Badge></div><p>{item.summary}</p><div className="tags">{(item.tags||[]).map(tag=><span key={tag}>{tag}</span>)}</div></div><Icon name={expanded===item.id?'down':'chevron'} size={18}/></button>{expanded===item.id&&<div className="knowledge-item-body"><p>{item.content||'暂无正文'}</p><div className="knowledge-source"><Icon name="info" size={15}/><span>来源：{item.source==='user'?'用户提供的产品架构文档与场景说明':item.source==='mock'?'演示案例中的专家反馈，尚需真实环境验证':'可复用的分析与实验方法'}{typeof item.case_id==='string'&&<> · <a href={`#cases/${item.case_id}`}>查看来源案例<Icon name="arrow" size={13}/></a></>}</span></div></div>}</article>)}</div>{filtered.length===0&&<Empty title="没有找到匹配的知识" detail="尝试其他关键词或分类。"/>}</section></>;
}
export function WorkflowsPage({items,onCreate}:{items:Workflow[];onCreate:(id:WorkflowId)=>void}) {
  const [selected,setSelected]=useState<WorkflowId>('version');
  const item=items.find(value=>value.id===selected);
  const defaultStages=['界定场景','采集证据','差异分析','根因假设','实验设计','专家确认','实验验证','沉淀复盘'];
  return <><div className="page-heading"><h1>工作流模板</h1><Badge tone="blue"><Icon name="workflow" size={14}/>LangGraph 编排</Badge></div><div className="template-grid">{items.map((value,index)=><button className={`template-card ${selected===value.id?'active':''}`} key={value.id} onClick={()=>setSelected(value.id)}><div className="section-heading"><span className={`track-icon track-${value.id}`}><Icon name={workflowIcons[value.id]} size={25}/></span><span className="template-index">0{index+1}</span></div><h2>{value.title}</h2><p>{value.description}</p><div className="template-select">{selected===value.id?'当前查看':'查看工作流'}<Icon name="arrow" size={16}/></div></button>)}</div><section className="panel workflow-detail"><div className="section-heading"><div><h2>{workflowLabels[selected]}工作流</h2><p>{item?.description}</p></div><button className="button button-primary" onClick={()=>onCreate(selected)}><Icon name="plus" size={16}/>使用此模板</button></div><div className="workflow-node-grid">{(item?.stages?.length?item.stages.map(value=>value.title):defaultStages).map((title,index)=><div className={`workflow-node ${index===5?'approval-node':''}`} key={index}><span>{String(index+1).padStart(2,'0')}</span><Icon name={['server','file','activity','spark','flask','shield','play','book'][index]} size={22}/><h3>{title}</h3><p>{['统一协议、版本与 fio 模型','收集指标、日志和环境配置','对齐基线，识别关键变化','关联证据，提出可验证判断','设定单变量与成功判据','记录专家确认与执行备注','保存前后对比与验证结果','沉淀结论与有效调优建议'][index]}</p></div>)}</div><div className="workflow-focus"><strong>场景关注点</strong><p>{formatContent(item?.focus)||'尚未配置'}</p></div></section></>;
}
export function ToolsPage({items}:{items:Tool[]}) {
  const [expanded,setExpanded]=useState<string|null>(null);
  return <><div className="page-heading"><h1>工具与能力</h1><Badge tone="amber">模拟适配器</Badge></div><div className="tool-summary"><div><Icon name="tool" size={24}/><strong>{items.length}</strong><span>已注册能力</span></div><div><Icon name="file" size={24}/><strong>{items.filter(item=>item.read_only===true).length}</strong><span>只读分析工具</span></div><div><Icon name="shield" size={24}/><strong>{items.filter(item=>item.requires_approval===true).length}</strong><span>需确认的实验工具</span></div></div><div className="tool-grid">{items.map(item=><article className="tool-card" key={item.id}><div className="section-heading"><span className="tool-icon"><Icon name={item.read_only?'file':'flask'} size={23}/></span><Badge tone="amber">模拟工具</Badge></div><h3>{item.title||item.name||item.id}</h3><p>{item.description}</p><div className="tool-metadata"><span>{item.read_only?'只读操作':'模拟实验'}</span><span>{item.requires_approval?'需专家确认':'自动分析'}</span></div><button className="tool-expand" onClick={()=>setExpanded(expanded===item.id?null:item.id)}>{expanded===item.id?'收起能力说明':'查看输入与输出'}<Icon name={expanded===item.id?'down':'chevron'} size={15}/></button>{expanded===item.id&&<div className="tool-config"><div><strong>工具标识</strong><code>{item.id}</code></div><div><strong>输入</strong><p>{formatContent(item.inputs)||'案例场景与已采集证据'}</p></div><div><strong>输出</strong><p>{item.output==='experiment'?'实验记录与前后对比':'可追溯证据资料'}</p></div><div><strong>运行方式</strong><p>演示模式。真实环境工具尚未接入。</p></div></div>}</article>)}</div></>;
}
